"""add_column_to_user

Revision ID: f6000476e58d
Revises: 3f9270c0450f
Create Date: 2026-05-26 11:38:30.394990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6000476e58d'
down_revision: Union[str, Sequence[str], None] = '3f9270c0450f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('mobile', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'end_date')
    op.drop_column('users', 'start_date')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'mobile')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
